name: Create Pull Request
on:
  push:
    branches:
      - master
jobs:
  syncDevelop:
    steps:
      - uses: peter-evans/create-pull-request@v3.1.0
        with:
          ref: develop
      - name: Ensure Master Updated
        run: |
          git fetch origin master:master
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3.1.0
        with:
          branch: develop

